name: Daily Slack Message

on:
  schedule:
    # Runs at 09:30 Berlin time (CET/CEST)
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C0AJFNX6U4R'  # Replace with your Slack channel ID
          slack-message: "STOKR Mining Updates - https://patrickatstokr.github.io/btc-mining-dashboard/"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
