name: Daily Slack Message

on:
  schedule:
    # This runs at 09:30 AM Berlin (Winter Time)
    - cron: '30 8 * * *' 
  workflow_dispatch: # This adds a "Run workflow" button for manual testing

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # REPLACE 'C12345678' with your actual Channel ID
          channel-id: 'C0AJFNX6U4R' 
          slack-message: "STOKR Mining Updates - https://patrickatstokr.github.io/btc-mining-dashboard/"
        env:
          # This refers to the secret you created in GitHub Settings
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 
